name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Extract version from pubspec.yaml
        id: version
        run: |
          version=$(grep '^version:' pubspec.yaml | cut -d ' ' -f2 | cut -d '+' -f1)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create .env file
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" > .env

      # Build APK
      - name: Build Android APK
        run: flutter build apk --release

      # Build AAB => Pour le Play Store
      # - name: Build Android App Bundle
      #   run: flutter build appbundle --release

      # # Build IPA
      # - name: Build iOS
      #   run: |
      #     flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      # Create GitHub Release with binaries
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Done
        run: echo "Release v${{ steps.version.outputs.version }} déployée avec succès !"